### PR TITLE
feat: implement rtl support for android picker

### LINKED ISSUE #218: RTL Support
this lib not support RTL view
Annotation 2021-02-22 150359
the `arrow-down` icon should be in left side not in right side as in pic

### PR DESCRIPTION
**Pull request by mateusz1913**
Hi, I added rtl support for android picker. To test that you can open example app and toggle switch which will trigger `I18nManager.forceRTL` method, after that app needs to be reloaded (neither state change, nor fast refresh does not work).

Closes #218

### CODE REVIEW

**Review by Naturalclar — APPROVED** [review]
@mateusz1913 LGTM! thanks so much 👍🏻

**Comment by mahmoudadel2231** [comment]
the issue still exists I have the latest version in android, it doesn't change the direction

**Comment by Alarees** [comment]
> the issue still exists I have the latest version in android, it doesn't change the direction

yes, but you need to add `android:supportsRtl="true"` in the `application` tag in `AndroidManifest.xml` file

**Pull request merged**
