### PR TITLE
fix: issue-180

### PR DESCRIPTION
**Pull request by jwboardman**
This fixes issue 180 https://github.com/react-native-picker/picker/issues/180

### CODE REVIEW

**Comment by jwboardman** [comment]
Is there someone who could re-run the android build? Looks like an intermittent failure "Received status code 502 from server: Bad Gateway".

**Comment by jwboardman** [comment]
Could I get a code review on this? What is the process to get it merged and released?

**Review by Naturalclar — APPROVED** [review]
@jwboardman thank you so much!

**Comment by jwboardman** [comment]
Awesome! Thank you!!

**Pull request merged**
