### PR TITLE
feat: Add multiline support to android picker

### PR DESCRIPTION
**Pull request by alesharik**
This PR adds `multiline` prop to android picker in order to support items with large labels

### CODE REVIEW

**Review by Naturalclar — APPROVED** [review]
@alesharik sorry for the late review! thanks so much for adding this feature!

**Comment by donni106** [comment]
> This PR adds `multiline` prop to android picker in order to support items with large labels

the prop is called `numberOfLines` and not `multiline`, right?
how does it look like in an android dialog? i cannot achieve the multiline behavior with latest version 1.16.5. my long entries are still ellipsed in one line. i tried with `numberOfLines={2}`.
thanks for any help or clearance.

**Comment by alesharik** [comment]
@donni106 
> the prop is called numberOfLines and not multiline, right?

Yes, it is.
> how does it look like in an android dialog?

photo_2021-08-05_22-56-50

**Comment by donni106** [comment]
i am on 1.16.1 now, but no matter what i am doing, it does not become multiline :( tried with `numberOfLines={2}` and larger `numberOfLines={5}`.

```
<Picker
  selectedValue={value}
  style={styles.pickerHeight}
  dropdownIconColor={colors.gray60}
  onValueChange={(pickerValue) => {
    onChange(pickerValue);
    Keyboard.dismiss();
  }}
  numberOfLines={5}
>
  ...
```

am i missing something?
i aleady restarted and tried with different android versions.
is maybe something missing from expo side to make this work?

**Comment by alesharik** [comment]
@donni106 Can you check what expo passes `numberOfLines` prop to real native component (`AndroidDialogPickerNativeComponent`)?

**Comment by donni106** [comment]
@alesharik thanks for your response. i cannot find anyhing with `numberOfLines` in their android java files here https://github.com/expo/expo/tree/e0bb254c889734f2ec6c7b688167f013587ed201/android/ReactAndroid/src/main/java/com/facebook/react/views/picker
i think it is missing. seems that the package is not fully updated to support latest features.

**Comment by alesharik** [comment]
@donni106 you found native module, which seems correct. But I was talking about JS wrapper around native module (`PickerAndroid`). I suspect that `numberOfLines` prop is not copied from user-facing component to native component (https://github.com/react-native-picker/picker/blob/master/js/PickerAndroid.android.js#L170). You should try to investigate with your IDE it there are any props lost in a copy process.

And did you try to reinstall `node_modules` from scratch (with removing the lock file)?

**Comment by donni106** [comment]
@alesharik hm i cannot answer exactly. i did delete and reinstall everything without success. when i go to `node_modules/@react-native-picker/picker/js/PickerAndroid.android.js` i can see the `numberOfLines` prop in the code and can log the passed number correctly when running my app. but the android dialog still remains single lined.

so i am stuck now again and do not know how to proceed debugging. i did not receive any reaction from expo side yet.

**Comment by alesharik** [comment]
@donni106 I found the possible cause of the issue in expo projects. Compare this expo condition (https://github.com/expo/expo/blob/master/android/expoview/src/main/java/versioned/host/exp/exponent/modules/api/components/picker/ReactPickerManager.java#L243) and original condition (https://github.com/react-native-picker/picker/blob/master/android/src/main/java/com/reactnativecommunity/picker/ReactPickerManager.java#L243). Expo is using android layouts, but they are broken and cannot do multiline.

**Comment by donni106** [comment]
wow, thanks very much @alesharik. i did not check that changes in the feature PR were touched afterwards so i assumed the master would be like the branch in the PR. i found the commit where the layout change from the feature PR was reverted and asked why. lets see if that helps somehow.

**Comment by donni106** [comment]
there is an open PR by Expo now https://github.com/expo/expo/pull/14104

**Pull request merged**
