### PR TITLE
fix: Change React peerDependencies version

### PR DESCRIPTION
**Pull request by FonDorn**

### CODE REVIEW

**Comment by stocaaro** [comment]
I would expect this change to resolve #425.

**Comment by ShivamEviView** [comment]
Waiting for this

**Comment by mufaddalhamidofficial** [comment]
Any progress, why is this not merged yet ?

**Comment by wortkotze** [comment]
Waiting for this 👍🏻

**Comment by srn271** [comment]
Waiting for this 👍🏼

**Comment by oscar-b** [comment]
In the meantime, you can add this to `package.json`:

```
  "overrides": {
    "react": "18.0.0"
  }
```

**Review by Naturalclar — COMMENTED** [review]
sorry for the late review! LGTM!

**Review by Naturalclar — APPROVED** [review]

**Pull request merged**
