### PR TITLE
Allow using custom font on android

### PR DESCRIPTION
**Pull request by camilossantos2809**

### CODE REVIEW

**Comment by developerdanx** [comment]
Hi :) , 

why is this PR still not merged? We need to pass custom style font to Picker Android.

**Comment by Macludde** [comment]
Please merge

**Comment by AdamTovatt** [comment]
Please merge this :-)

**Comment by Naturalclar** [comment]
@camilossantos2809 thanks for the PR! would you be able to resolve the merge conflict when you have the chance?

**Comment by camilossantos2809** [comment]
@Naturalclar merge conflicts resolved :)

**Pull request merged**
