### PR TITLE
feat: Support RN 0.74 and Bridgeless

### PR DESCRIPTION
**Pull request by alanjhughes**
Update library to work with react native 0.74 and bridgeless. The main changes being
- The removal of `FabricViewStateManager.HasFabricViewStateManager` and replacing it with `StateWrapper`
- Some changes to c++ function arguments and using c++20
- Add the same `.clang-format` that react native uses to clean up some formatting issues.

### Tested on 
- Old arch ✅
- New arch 
   - with bridgeless enabled 
      - iOS ✅
      - Android  ✅
   - with bridgeless disabled
      - iOS ✅
      - Android ✅

~~Note: There is currently a bug in RC2 that causes an error on android when using the new arch with bridgeless disabled. This will be resolved in RC3~~
Issue has been resolved in RC3 and I have bumped the example. Everything is working correctly now

### CODE REVIEW

**Comment by brentvatne** [comment]
looking forward to this landing and getting us one step closer to new arch support in the ecosystem!

**Comment by DavideViolante** [comment]
I think this PR is causing #555 #556 #557

**Comment by tortuvshin** [comment]
> I think this PR is causing #555 #556 #557

I faced the same error

**Pull request merged**
